// <auto-generated />
using FileSaver.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FileSaver.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FileSaver.Models.FileModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AltLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Before")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Definition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Deprecated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HasRelatedSynonym")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HiddenLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IRI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InverseOf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsAuthor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsDefinedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkFirst")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("http://webprotege.stanford.edu/RBwBJ2lKdRgVYPkQmoJN1pD");

                    b.Property<string>("LinkSecond")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("http://webprotege.stanford.edu/RCAWR19VGcj184M2SBAaeoj");

                    b.Property<string>("LocatedIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrefLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sali_appealsTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sali_cited")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sali_filed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sali_hasExpense")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sali_participatedIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sali_seealso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sali_seeksToAchieve")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sali_workedFor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SameAs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeeAlso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Superclass")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Superclass(es)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("legacyIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("FileModels");
                });

            modelBuilder.Entity("FileSaver.Models.Filess", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileId"));

                    b.Property<string>("FileContent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FileId");

                    b.ToTable("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
